version: '2'
services:
  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=ec_sample
      - LANG=C.UTF-8
    volumes:
      - db:/var/lib/mysql
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    image: arbiedev/php-nginx:7.3
    working_dir: /var/www/laravel
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/laravel
      - ./nginx.conf:/etc/nginx/sites-enabled/default

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3333:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - db
    volumes:
      - ./phpmyadmin/sessions:/sessions

volumes:
  db:
